let Settings = {
  NUMBER_OF_PARTICLES: 10,
  FIELD_SCALE: 40,
  FORCE_STRENGTH: 0.6,
  OFFSET_SPEED: 0.08,
  TIME_OFFSET_SPEED: 0.01,
  DETAIL: 15,

  MAX_SPEED: 5,
  THICKNESS: 5,
  ALPHA: 255,

  USE_RAINBOW: true,
  DRAW_VECTORS: false,
  DRAW_PARTICLES: true,
  DRAW_FPS: true,

  Field: {
    ENABLE_TIME: true,
  },
};
