let Settings = {
  NUMBER_OF_PARTICLES: 10,
  FIELD_SCALE: 50,
  FORCE_STRENGTH: 0.6,
  OFFSET_SPEED: 0.08,
  TIME_OFFSET_SPEED: 0.01,
  DETAIL: 15,

  MAX_SPEED: 5,
  THICKNESS: 5,
  ALPHA: 255,

  DRAW_VECTORS: false,
  DRAW_PARTICLES: false,
  DRAW_NOISE: true,
  DRAW_FPS: false,
  USE_RAINBOW: false,
};
